name: Build and Publish Agent Portal

on:
  push:
    branches: [ main ]
    paths:
    - 'AgentPortal/**'

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Setup .Net Environment'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.202

      - name: 'Project Dependencies'
        shell: pwsh
        run: |
          cd ./AgentPortal
          dotnet restore

      - name: 'Build project'
        shell: pwsh
        run: |
          cd ./AgentPortal
          dotnet build -c Release
          
      - name: 'Publish'
        shell: pwsh
        run: |
          cd ./AgentPortal
          dotnet publish

      - name: Upload Agent Portal Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Agent Portal
          path: D:\a\ElectricityBillTopUp\ElectricityBillTopUp\AgentPortal\bin\Debug\net5.0\publish\