name: Build and Publish Agent Poertal

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.202
 
    - name: Install dependencies
      run: dotnet restore ./AgentPortal/*
      
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish