name: Build and Publish Customer Portal

on:
  push:
    branches: [ main ]
    paths:
      - 'CustomerPortal/**'

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v2

      - name: Setup .Net Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'
          
      - name: Build project
        shell: pwsh
        run: |
          dotnet build -c Release
          
      - name: Publish
        run: dotnet publish
